Scrum 48
gfa-cc-after/Pet-Clinic-GilmoreDevs pull request #31
Opened 2024-07-13 12:26 UTC by markkovari

2024-07-15 19:58 UTC, markkovari commented
I messed this up a little bit, I will remove the local commit hook related things before class and we can quickly go through it.

2024-07-16 16:07 UTC, Hsbalazs requested changes

2024-07-16 16:08 UTC, markkovari commented on frontend/src/pages/Register.tsx
> +setMessage (" ");
```suggestion
setMessage (" ");
```

2024-07-16 16:10 UTC, markkovari commented on frontend/src/pages/Register.test.tsx
> +    });
```suggestion
```

2024-07-16 16:11 UTC, ramesz6 approved these changes

2024-07-16 16:11 UTC, Hsbalazs approved these changes

2024-07-16 16:12 UTC, merged