SCRUM 74: Add the dependency with the necessary secrets
gfa-cc-after/Pet-Clinic-GilmoreDevs pull request #82
Opened 2024-08-21 18:59 UTC by carlos-ponton

- **chore: add the SpringBoot Starter Mail dependency**
- **chore: add Mail Server properties and secret keys**

2024-08-22 06:09 UTC, markkovari requested changes
Can you help us out @carlos-ponton how to get these environment variables or how to use them?

2024-08-22 12:21 UTC, markkovari approved these changes

2024-08-23 15:07 UTC, ramesz6 approved these changes

2024-08-25 09:59 UTC, AnnaUgrai approved these changes
![image](https://github.com/user-attachments/assets/c1ea960e-a2e0-4baf-903f-f60758fc785d)

2024-08-25 10:00 UTC, markkovari commented
![image](https://github.com/user-attachments/assets/382167db-6318-47f9-b806-dffa34df5962)

2024-08-26 10:51 UTC, merged